name: ReplantPls
version: '${version}'
main: lol.hyper.replantpls.ReplantPls
api-version: '26.1.1'
author: hyperdefined
website: https://github.com/hyperdefined/ReplantPls
description: Replant crops more easily!
folia-supported: true
softdepend: [mcMMO]
loader: lol.hyper.replantpls.ReplantPlsLoader