name: ReplantPls
version: '${project.version}'
main: lol.hyper.replantpls.ReplantPls
api-version: 1.21
author: hyperdefined
website: https://github.com/hyperdefined/ReplantPls
description: Replant crops more easily!
folia-supported: true
softdepend: [mcMMO]